title: "Sampling Algorithms Tutorial"
description: "A comprehensive guide to sampling algorithms with interactive notebooks"
baseurl: "/library-of-sampling-methods" # the subpath of your site
url: "https://charles-kmc.github.io" # your GitHub Pages URL
github_username: charles-kmc

# Build settings
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Markdown settings
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Collections
collections:
  tutorials:
    output: true
    permalink: /:collection/:name

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Joel & Charlesquin"
  - scope:
      path: ""
    values:
      layout: "default"

# start configuration
collections:
  start:
    output: true
    permalink: /start/:name/
  tutorials:
    output: true
    permalink: /:collection/:name
  tools:
    output: true
    permalink: /tools/:path/
  examples:
    output: true
    permalink:/examples/:path

defaults:
  - scope:
      path: ""
      type: "tools"
    values:
      layout: "tool"
      author: "Joel & Charlesquin"
  - scope:
      path: ""
      type: "start"
    values:
      layout: "start-tutorial"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
    scope:
      path: ""
      type: "examples"
    values:
      layout: "example"
  - scope:
      path: ""
    values:
      layout: "default"
